baseURL = 'https://adidumitre.github.io/adidumitreblog/'
languageCode = 'en-us'
title = 'Blog'

theme = 'contrast-hugo'

[params]
  minimal = false
  excerpts = false
  description = "my blog"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
